fitj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import routines.views
import workouts.views

urlpatterns = [
    url(r'^$', workouts.views.index, name='index'),
    url(r'^db/', routines.views.db, name='db'),
    url(r'^routines/', include('routines.urls')),
    url(r'^workouts/', include('workouts.urls')),
    url(r'^admin/', admin.site.urls),
]

workouts/urls.py
from django.conf.urls import url

from . import views

app_name = 'workouts'
urlpatterns = [
  # e.g. /workouts
  url(r'^$', views.index, name='index'),
  # e.g. /workouts/login
  url(r'^login/$', views.login, name='login'),
  # e.g. /workouts/logout
  url(r'^logout/$', views.logout, name='logout'),
  # e.g. /workouts/sign_up
  url(r'^sign_up/$', views.sign_up, name='sign_up'),
  # e.g. /workouts/trending
  url(r'^trending/$', views.trending, name='trending'),
  # e.g. /workouts/profile
  url(r'^profile/$', views.profile, name='profile'),
  # e.g. /workouts/journal
  url(r'^journal/$', views.journal, name='journal'),
  # e.g. /workouts/user
  url(r'^user/$', views.user, name='user'),
  # e.g. /workouts/user/2
  url(r'^user/(?P<user_id>[0-9]+)/$', views.user_detail, name='user_detail'),
  # e.g. /workouts/user/2/follow
  url(r'^user/(?P<user_id>[0-9]+)/follow/$', views.follow_user, name='follow_user'),
  # e.g. /workouts/2
  url(r'^(?P<routine_id>[0-9]+)/$', views.detail, name='detail'),
  # e.g. /workouts/2/edit
  url(r'^(?P<routine_id>[0-9]+)/edit/$', views.edit_routine, name='edit_routine'),
  # e.g. /workouts/2/customize
  url(r'^(?P<routine_id>[0-9]+)/customize/$', views.customize_routine, name='customize_routine'),
  # e.g. /workouts/2/results
  url(r'^(?P<routine_id>[0-9]+)/results/$', views.results, name='results'),
  # e.g. /workouts/add/routine
  url(r'^add/routine/$', views.add_routine, name='add_routine'),
  # e.g. /workouts/2/add/exercise
  url(r'^(?P<routine_id>[0-9]+)/add/exercise/$', views.add_exercise, name='add_exercise'),
  # e.g. /workouts/sort_by_likes
  url(r'^sort_by_likes/$', views.sort_by_likes, name='sort_by_likes'),

]

workouts/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

import datetime

# Create your models here.
class Routine(models.Model):
  routine_title = models.CharField(max_length=70)
  routine_text = models.TextField()
  pub_date = models.DateTimeField('date published', default=timezone.now)
  created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="created_by")
  modify_date = models.DateTimeField('date modified', null=True)
  modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name="modified_by")
  likes = models.IntegerField(default=0)
  def __str__(self):
    return self.routine_title
  

class Exercise(models.Model):
  routine = models.ForeignKey(Routine, on_delete=models.CASCADE)
  exercise_text = models.CharField(max_length=200)
  pub_date = models.DateTimeField('date published')
  likes = models.IntegerField(default=0)
  def was_published_recently(self):
    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
  def __str__(self):
    return self.exercise_text


class Comment(models.Model):
  created_by = models.ForeignKey(settings.AUTH_USER_MODEL)
  routine = models.ForeignKey(Routine, on_delete=models.CASCADE)
  comment_text = models.TextField(max_length=1000)
  pub_date = models.DateTimeField('date published')
  likes = models.IntegerField(default=0)
  def __str__(self):
    return self.comment_text


class Tag(models.Model):
  routine = models.ForeignKey(Routine, on_delete=models.CASCADE)
  tag_text = models.CharField(max_length=70)
  def __str__(self):
    return self.tag_text


class Comment_Routine(models.Model):
  routine = models.ForeignKey(Routine, on_delete=models.CASCADE)
  comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
  def __str__(self):
    return self.comment.comment_text


class Follower(models.Model):
  # user = models.ForeignKey(User, related_name="user")
  user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="user")
  follower = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="follower")
  create_date = models.DateTimeField('date created')
  def __str__(self):
    return self.user.username

class Journal(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  routine = models.ForeignKey(Routine, on_delete=models.CASCADE)
  completed_on = models.DateTimeField(null=True)
  completed_count = models.IntegerField(default=0)
  def __str__(self):
    return self.routine.routine_title

class Like(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  routine = models.ForeignKey(Routine, on_delete=models.CASCADE)
  pub_date = models.DateTimeField(default=timezone.now)
  def __str__(self):
    return self.routine.routine_title


class Results(models.Model):
  # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  # routine = models.ForeignKey(Routine, on_delete=models.CASCADE)
  journal_entry = models.ForeignKey(Journal, on_delete=models.CASCADE)
  results_text = models.TextField(max_length=1000)
  completed_date = models.DateTimeField(default=timezone.now)
  def __str__(self):
    return str(self.completed_date.date())

workouts/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import F
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import authenticate
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User 
from django.contrib.auth.decorators import login_required

from .models import Routine, Comment, Journal, Tag, Results
from .utils import valid_name, valid_username, valid_password, valid_email, valid_title, valid_content_input, valid_tag_list, valid_digit, valid_routine_form, get_page_num


# Create your views here.
# TODO create recommendations based on likes
# TODO create search functionality
# TODO convert index numbers to title of workouts
# TODO show other users' journals? Recently completed items.
def index(request):
  RESULTS_PER_PAGE = 10
  if request.method == 'GET':
    s = request.GET.get('start', 0)
    tags = request.GET.get('tags', None)
    sort = request.GET.get('sort', '-likes')
    if valid_digit(s):
      s = int(s)
    # get the current page results
    if tags:
      routine_list = Routine.objects.filter(tag__tag_text=tags).order_by(sort)[s:s + RESULTS_PER_PAGE]
      results_remaining = Routine.objects.filter(tag__tag_text=tags).order_by(sort)[s + RESULTS_PER_PAGE:].exists()
    else:
      routine_list = Routine.objects.order_by(sort)[s:s + RESULTS_PER_PAGE]
      results_remaining = Routine.objects.order_by(sort)[s + RESULTS_PER_PAGE:].exists()
    # get the current page number
    current_page = get_page_num(s)
    # initialize params
    params = {'list': routine_list, 'current_page': current_page, 'tags': tags, 'sort': sort}
    # check if next results and get next page number
    # results_remaining = Routine.objects.count() - RESULTS_PER_PAGE - s
    if results_remaining:
      next_start = s + RESULTS_PER_PAGE
      params['next_start'] = next_start
      params['next_page'] = get_page_num(next_start)
    # check if prev results and get prev page number
    prev_start = s - RESULTS_PER_PAGE
    if prev_start >= 0:
      params['prev_start'] = prev_start
      params['prev_page'] = max(get_page_num(prev_start), 1)
    print (params)
    return render(request, 'workouts/index.html', params)

def login(request):
  if request.method == "POST":
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
      auth_login(request, user)
      return HttpResponseRedirect(reverse("workouts:index"))
    else:
      # return an 'invalid login' error message
      return render(request, "workouts/login.html", {
        "error_message" : "Username and password did not match",
        "username" : username,
        })
  else:
    return render(request, 'workouts/login.html')

def logout(request):
  auth_logout(request)
  return render(request, "workouts/logout.html")

def profile(request):
  if not request.user.is_authenticated:
    return HttpResponseRedirect(reverse('workouts:login'))
  else:
    return render(request, "workouts/profile.html") 

def sign_up(request):
  if request.method == "POST":
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    error_exists = False
    params = dict(first_name=first_name, last_name=last_name, email=email)

    if not valid_name(first_name) or not valid_name(last_name):
      error_exists = True
      params['error_name'] = "Enter a first and last name using only letters, apostrophes and hyphens"
    if not valid_username(username):
      error_exists = True
      params['error_username'] = "Enter a username using only letters, numbers, underscore and hyphens"
    if not valid_email(email):
      error_exists = True
      params['error_email'] = "Please enter in the format example@domain.com"
    if not valid_password(password):
      error_exists = True
      params['error_password'] = "Minimum password length is 6 characters"
    if error_exists:
      return render(request, "workouts/sign_up.html", params)

    user = User(first_name = first_name,
                last_name = last_name,
                email = email,
                username = username)
    user.set_password(password)
    user.save()
    # TODO add sign up success message to login
    return HttpResponseRedirect(reverse("workouts:login"))
  else:
    return render(request, "workouts/sign_up.html")

@login_required()
def journal(request):
  journal = Journal.objects.filter(user=request.user)
  journal_planned = journal.filter(completed_count=0)
  journal_completed = journal.filter(completed_count__gt=0)

  params = dict(journal_planned=journal_planned, 
                journal_completed=journal_completed)

  if request.method == 'POST':
    if 'entry_id' in request.POST:
      error_exists = False
      entry_id = request.POST['entry_id']
      if not valid_digit(entry_id):
        error_exists = True
        params['error_entry_id'] = "The journal entry did not match any records"
      if error_exists:
        return render(request, 'workouts/journal.html', params)

      entry_id = int(entry_id)
      entry = get_object_or_404(Journal, user=request.user, pk=entry_id)

      # if 'mark_complete' in request.POST:
      #   entry.completed_count = F('completed_count') + 1
      #   entry.completed_on = timezone.now()
      #   entry.save()
      #   return HttpResponseRedirect(reverse("workouts:results", args=[entry_id]))
      if 'remove_from_journal' in request.POST:
        entry.delete()

  return render(request, "workouts/journal.html", params)

@login_required()
def results(request, routine_id):
  routine = get_object_or_404(Routine, pk=routine_id)
  entry = Journal.objects.filter(user=request.user, routine__id=routine_id).get()
  # entry = Journal.objects.filter(user=request.user, routine__id=routine_id)
  params = dict(routine=routine, results=entry.results_set.all())
  if request.method == "POST":
    results_text = request.POST.get("results_text")
    if not results_text:
      results_text = "As prescribed"
    entry.results_set.create(results_text=results_text)
    params['record_results_success'] = "Successfully recorded results"

    entry.completed_count = F('completed_count') + 1
    entry.save()

    return render(request, "workouts/results.html", params)
  else:
    return render(request, "workouts/results.html", params)


# TODO add delete comment capability
def detail(request, routine_id):
  routine = get_object_or_404(Routine, pk=routine_id)
  params = dict(routine=routine)
  if request.user.is_authenticated:
    if request.user.journal_set.filter(routine=routine).exists():
      params['routine_exists_in_journal'] = True
  if request.method == 'POST':
    if "add_to_journal" in request.POST:
      if not request.user.is_authenticated:
        params['error_add_to_journal'] = "You must log in first"
        return render(request, 'workouts/detail.html', params)
      if request.user.journal_set.filter(routine=routine).exists():
        params['error_add_to_journal'] = "Already added to journal"
        return render(request, "workouts/detail.html", params)
      entry = Journal(user=request.user, routine=routine)
      entry.save()
      params['routine_exists_in_journal'] = True
      params['add_to_journal_success'] = "Added routine to journal"
      return render(request, "workouts/detail.html", params)
    if "like" in request.POST:
      if not request.user.is_authenticated:
        params['error_like'] = "You must log in first"
        return render(request, 'workouts/detail.html', params)
      # get row out of db
      l = request.user.like_set.filter(routine=routine)
      if l.exists():
        routine.likes = F('likes') - 1
        routine.save()
        l.get().delete()
      else:
        routine.likes = F('likes') + 1
        routine.save()
        request.user.like_set.create(routine=routine)
      # reload the object to show the DB update
      params['routine'] = Routine.objects.filter(pk=routine_id).get()
      return render(request, "workouts/detail.html", params)
    # TODO ask for confirmation to delete (pop-up)
    if "delete_routine" in request.POST:
      if request.user.is_authenticated:
        if request.user != routine.created_by:
          params['error_delete'] = "you aren't the creator of this routine"
          return render(request, 'workouts/detail.html', params)
        routine.delete()
        return HttpResponseRedirect(reverse('workouts:index'))
    if "comment" in request.POST:
      if request.user.is_authenticated:
        comment_text = request.POST["comment_text"]
        params = dict(routine=routine, comment_text=comment_text)
        if not valid_content_input(comment_text):
          params['error_text'] = "Please enter the details"
          return render(request, 'workouts/detail.html', params)
        routine.comment_set.create(created_by=request.user,
                                   comment_text=comment_text,
                                   pub_date=timezone.now())
        return HttpResponseRedirect(reverse('workouts:detail', args=[routine.id]))
    if "mark_complete" in request.POST:
      if not request.user.is_authenticated:
        params['error_delete'] = "Add this routine to your journal before marking complete"
        return render(request, 'workouts/detail.html', params)
      entry = request.user.journal_set.filter(routine=routine)
      entry.update(completed_count=F('completed_count') + 1)
      entry.get().results_set.create(results_text="As prescribed")
      return HttpResponseRedirect(reverse("workouts:detail", args=[routine.id]))

    # redirect anonymous users to login
    return HttpResponseRedirect(reverse('workouts:login'))
  else:

workouts/templates/workouts/add_exercise.html
{% extends "./base.html" %}

{% block content %}
<h1>Add a new exercise</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form method="post">
{% csrf_token %}
  <div>
  <label for="exercise_text">Exercises (separate with new line)</label></br>
  <textarea name="exercise_text" style="height: 200px; width: 400px;">{{exercise_text}}</textarea>
  </div>
  <input type="submit" value="Add exercise"/>
</form>
{% endblock %}

workouts/templates/workouts/add_to_journal.html
{% extends "./base.html" %}

{% block content %}
<h1>Add {{ routine.routine_title }} to journal?</h1>

<form method="post">
{% csrf_token %}
  <input type="submit" value="Add routine"/>
</form>
{% endblock %}

workouts/templates/workouts/add_user.html
{% extends "./base.html" %}

{% block content %}
<h1>Add a new user</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form method="post">
{% csrf_token %}
  <div>
  <label for="username">Username</label></br>
  <input type="text" name="username" />
  </div>
  <input type="submit" value="Add" />
</form>
{% endblock %}

workouts/templates/workouts/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/workouts/icons/logo1_16.png">

    <title>{% block title %}Fit-j{% endblock %}</title>
    
    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'workouts/css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'workouts/css/style.css' %}" rel="stylesheet" type="text/css">
    
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <!-- <link href="starter-template.css" rel="stylesheet"> -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>



  <body>
    <nav class="navbar navbar-default">
      <div class="container">
      {% block sidebar %}
        <div id="navbar" class="">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'workouts:index' %}">Home</a></li>
            <li><a href="{% url 'workouts:index' %}?sort=-pub_date">Recent</a></li>
            <!-- <li><a href="{% url 'workouts:sort_by_likes' %}">Top</a></li> -->
            <!-- <li><a href="{% url 'workouts:trending' %}">Trending</a></li> -->
            <li><a href="{% url 'workouts:user' %}">User</a></li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'workouts:profile' %}">{{ user.first_name }}</a></li>
              <li><a href="{% url 'workouts:journal' %}">Journal</a></li>
              <li><a href="{% url 'workouts:logout' %}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'workouts:login' %}">Login</a></li>
              <li><a href="{% url 'workouts:sign_up' %}">Sign up</a></li>
            {% endif %}
          </ul>
      {% endblock sidebar %}
      </div>
    </nav>

    <div id="content" class="container">
      {% block content %}{% endblock %}
    </div> <!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'workouts/js/bootstrap.js' %}"></script>
    <!-- <script src="../../static/workouts/js/bootstrap.min.js"></script> -->
    <!-- <script src="../../assets/js/docs.min.js"></script> -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
  </body>





</html>

workouts/templates/workouts/detail.html
{% extends "./base.html" %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>{{ routine.routine_title }}</h1>
    <h4><small>Created {{ routine.pub_date }} by <a href="{% url 'workouts:user_detail' routine.created_by.id %}">{{ routine.created_by.first_name }}</a></small></h4>
  </div>
</div>
<div class="row">
  <div class="col-md-9">
    <pre>{{ routine.routine_text }}</pre>
  </div>
  <div class="col-md-3">
    {% for tag in routine.tag_set.all %}
      <span><a class="badge" href="{% url 'workouts:index' %}?tags={{ tag.tag_text }}">{{ tag.tag_text }}</a></span>
    {% endfor %}
  </div>
</div>

<div class="row">
  <div class="col-md-9">
    <form method="post">
      {% csrf_token %}

      {% if user.is_authenticated %}
        <button type="submit" name="like" class="btn btn-default">Like <span class="badge">{{ routine.likes }}</span></button>
        {% if routine_exists_in_journal is True %}
          <!-- Split button -->
          <div class="btn-group">
            <button type="submit" class="btn btn-default" name="mark_complete">Mark complete</a></button>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="caret"></span>
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
              <li><a href="{% url 'workouts:results' routine.id %}"">Log results</a></li>
            </ul>
          </div>
        {% else %}
          <button type="submit" name="add_to_journal" class="btn btn-default">Add to journal</button>
        {% endif %}
        <a class="btn btn-default" href="{% url 'workouts:customize_routine' routine.id %}">Customize</a>
      {% endif %}
      {% if user == routine.created_by %}
        <a class="btn btn-default" href="{% url 'workouts:edit_routine' routine.id %}">Edit</a>
        <button class="btn btn-danger" type="submit" name="delete_routine">Delete routine</button>
      {% endif %}

    </form>
  </div>
</div>

<div class="alert-info">{{ error_delete }}</div>
<div class="alert-info">{{ error_add_to_journal }}</div>
<div class="alert-success">{{ add_to_journal_success }}</div>

<div class="row">
  <div class="col-md-9">
    {% if routine.comment_set.exists %}
      <h2>Comments</h2>
      {% for comment in routine.comment_set.all %}
        <p>
          <a href="{% url 'workouts:user_detail' comment.created_by.id %}">
            <strong>{{ comment.created_by }} </strong>
          </a>
          {{ comment.comment_text }}
        </p>
      {% endfor %}
    {% endif %}
    
      <form method="post">
        {% csrf_token %}
        <div class="form-group"><textarea name="comment_text" class="form-control" rows="3" placeholder="Leave a comment"></textarea></div>
        <div><button type="submit" name="comment" class="btn btn-md btn-default">Comment</button></div>
        <div>{{ error_text }}</div>
      </form>
  </div>
</div>

{% endblock content %}

workouts/templates/workouts/follow_user.html
{% extends "./base.html" %}

{% block content %}
<h1>Follow more:</h1>

<form method="post">
  {% csrf_token %}
	{% for user in list %}
		<input type="checkbox" name="follow" value="{{ user.id }}" 
			{% if user.id in current_following %}
				checked				
			{% endif %}
    >{{ user.username }} 
    </br>
  {% endfor %}
  <input type="submit" value="Follow"/>
</form>

{% endblock content %}

workouts/templates/workouts/journal.html
{% extends "./journal_browse.html" %}

{% block journal_title %}
<div class="page-header"><h1>Your Journal</h1></div>
{% endblock %}

{% block journal_planned_buttons %}
<span>
  <p>
    <form method='post'>
      {% csrf_token %}
      <input type="hidden" name="entry_id" value="{{ entry.id }}" />
      <span><button type="submit" name="mark_complete" class="btn btn-xs btn-default">Mark complete</button></span>
      <span><button type="submit" name="remove_from_journal" class="btn btn-xs btn-default">Remove from journal</button></span>
    </form>
  </p>
</span>
{% endblock %}

{% block journal_completed_buttons %}
<p>
  <form method='post'>
    {% csrf_token %}
    <input type="hidden" name="entry_id" value="{{ entry.id }}" />
    <span><button type="submit" name="mark_complete" class="btn btn-xs btn-default">Mark complete</button></span>
    <span><button type="submit" name="remove_from_journal" class="btn btn-xs btn-default">Remove from journal</button></span>
  </form>
</p>
{% endblock %}

workouts/templates/workouts/journal_personal.html
{% extends "./journal.html" %}

{% block journal_planned_buttons %}
<span>
  <form method='post'>
    {% csrf_token %}
    <input type="hidden" name="entry_id" value="{{ entry.id }}" />
    <span><input type="submit" name="mark_complete" value="Mark complete" /></span>
    <span><input type="submit" name="remove_from_journal" value="Remove from journal" /></span>
  </form>
</span>
{% endblock %}

{% block journal_completed_buttons %}
<form method='post'>
  {% csrf_token %}
  <input type="hidden" name="entry_id" value="{{ entry.id }}" />
  <span><input type="submit" name="mark_complete" value="Mark complete" /></span>
  <span><input type="submit" name="remove_from_journal" value="Remove from journal" /></span>
</form>
{% endblock %}

workouts/templates/workouts/login.html
{% extends "./base.html" %}

{% block content %}
<div class="col-md-6">
<form method="post">
  {% csrf_token %}

  <div class="form-group">
  	<label for="username">Username</label>
    <input type="text" id="username" class="form-control" name="username" value="{{ username }}"/>
  </div>

  <div class="form-group">
  	<label for="password">Password</label>
  	<input type="password" id="password" class="form-control" name="password" />
  </div>

  <div><button type="submit" class="btn btn-md btn-default">Submit</button></div>

  <div>{{ error_message }}</div>
</form>
</div>
{% endblock content %}

workouts/templates/workouts/logout.html
<div>Successfully logged out</div>
<div><a href="{% url 'workouts:index' %}">Home</a></div>

workouts/templates/workouts/profile.html
{% extends "./base.html" %}

{% block content %}
<h1>{{ user.username }}</h1>

<div>
  <span>First name: </span>
  <span>{{ user.first_name }}</span>
</div>

<div>
  <span>Last name: </span>
  <span>{{ user.last_name }}</span>
</div>

<div>
  <span>Email: </span>
  <span>{{ user.email }}</span>
</div>
{% endblock content %}

workouts/templates/workouts/results.html
{% extends "./base.html" %}

{% block content %}
<div>
  <h1>{% block title %}Results{% endblock %}</h1>
</div>

<form method="post">
{% csrf_token %}
  <div class="row">
    <div class="col-md-12">
      <label for="routine_text">{{ routine.routine_title }} original routine</label>
      <pre id="routine_text">{{ routine.routine_text }}</pre>
    </div>
    <div class="col-md-12">
      <label for="results_text">Enter results here</label>
      <textarea id="results_text" name="results_text" placeholder="e.g. as prescribed"></textarea>
      <span>{{ error_text }}</span>
      <div class="alert-success">{{ record_results_success }}</div>
      <input type="submit" value="Submit"/>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h2>Previous results:</h2>
    </div>
    {% if results %}
      {% for r in results %}
        <div class="col-md-6">
          <div>{{ r.completed_date }}</div>
          <div>{{ r.results_text }}</div>
        </div>
      {% endfor %}
    {% else %}
      <div class="col-md-6">None</div>
    {% endif %}
  </div>
</form>
{% endblock %}

workouts/templates/workouts/user.html
{% extends "./base.html" %}

{% block content %}
<div class="page-header"><h1>User Index</h1></div>

{% if list %}
    <ul>
    {% for user in list %}
        <li>
          <a href="{% url "workouts:user_detail" user.id %}">{{ user.username }}</a>
          <span>{{ user.count_followers }}</span>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No users are available.</p>
{% endif %}
{% endblock content %}

workouts/templates/workouts/user_detail.html
{% extends "./base.html" %}

{% block content %}
<h1>{{ user.username }}</h1>

<div>
<h2>Users you currently follow:</h2>
<ul>
	{% for following in user.follower.all %}
    <li><a href="{% url 'workouts:user_detail' following.user.id %}">{{ following.user.username }}</a></li>
  {% endfor %}
  <li><a href="{% url "workouts:follow_user" user.id %}">Follow more</a></li>
</ul>
</div>

<div>
<h2>Routines you currently follow:</h2>
<ul>
	{% for routine in user.user_routine_set.all %}
    <li><a href="{% url "workouts:detail" routine.routine.id %}">{{ routine.routine.routine_text }}</a></li>
  {% endfor %}
  <li><a href="{% url "workouts:index" %}">Browse all routines</a></li>
</ul>
</div>

<div>
<h2>Comments you recently made:</h2>
<ul>
	{% for comment_routine in output_list %}
    <strong>{{ comment_routine.routine.routine_text }}</strong></br>
    {{ comment_routine.comment.comment_text }}</br>
  {% endfor %}
</ul>
</div>

<div>
<form method="post">
  {% csrf_token %}
  <input type="submit" value="Delete user"/>
</form>
</div>
{% endblock content %}