fitj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import routines.views
import workouts.views

urlpatterns = [
    url(r'^$', workouts.views.index, name='index'),
    url(r'^db/', routines.views.db, name='db'),
    url(r'^routines/', include('routines.urls')),
    url(r'^workouts/', include('workouts.urls')),
    url(r'^admin/', admin.site.urls),
]

routines/urls.py
from django.conf.urls import url

from . import views

app_name = 'routines'
urlpatterns = [
  # e.g. /routines
  url(r'^$', views.index, name='index'),
]

routines/models.py
from django.db import models

# Create your models here.
class Greeting(models.Model):
    when = models.DateTimeField('date created', auto_now_add=True)

class Workout(models.Model):
  """Workout represents one WOD. May contain duplicates."""
  __tablename__ = 'workouts'

  title = models.CharField(max_length=255)
  description = models.TextField()
  results_best = models.CharField(max_length=255, null=True)
  results_worst = models.CharField(max_length=255, null=True)
  results_avg = models.CharField(max_length=255, null=True)
  results_best_male = models.CharField(max_length=255, null=True)
  results_worst_male = models.CharField(max_length=255, null=True)
  results_avg_male = models.CharField(max_length=255, null=True)
  results_best_female = models.CharField(max_length=255, null=True)
  results_worst_female = models.CharField(max_length=255, null=True)
  results_avg_female = models.CharField(max_length=255, null=True)

  def __repr__(self):
    return "<Workout(title='%s', description='%s')>" % (self.title, self.description)

class User(models.Model):
  """Users that leave comments for the workout."""
  __tablename__ = 'users'

  username = models.CharField(max_length=255) 

  def __repr__(self):
    return "<User(username='%s')>" % (self.username)

class Comment(models.Model):
  """Comments for each workout."""
  __tablename__ = 'comments'

  text = models.TextField()
  workout = models.ForeignKey(Workout, null=True)
  user = models.ForeignKey(User, null=True)

  def __repr__(self):
    return "<Comment(text='%s')>" % (self.text)


class Result(models.Model):
  """Result of a user performing a workout"""
  __tablename__ = 'results'

  workout = models.ForeignKey(Workout, null=True)
  comment = models.ForeignKey(Comment, null=True)
  user = models.ForeignKey(User, null=True)
  gender = models.CharField(max_length=255, null=True)
  age = models.IntegerField(null=True)
  height = models.CharField(max_length=255, null=True)
  weight = models.IntegerField(null=True)
  result = models.CharField(max_length=255, null=True)
  score = models.IntegerField(null=True)
  units = models.CharField(max_length=255, null=True)
  mods = models.CharField(max_length=255, null=True)

  def __repr__(self):
    return "<Result('%s %s')>" % (self.result, self.units)

routines/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import F
from django.urls import reverse

from .models import Workout, User, Comment, Result


# Create your views here.
def index(request):
    params = {'workout_title': 'Fran',
              'workout_description': '21-15-9 Pull Ups Thrusters 95#', 
              'workout_results_best_male': '4:30', 
              'workout_results_avg_male': '5:30',
              'workout_results_worst_male': '7:30',
              'workout_results_best_female': '5:55',
              'workout_results_avg_female': '7:30',
              'workout_results_worst_female': '10:00'}
    # workout = get_object_or_404(Workout, id=1)
    # params = {'workout': workout}
    return render(request, 'routines/index_dynamic.html', params)
    # return render(request, 'index.html')


def db(request):

    greeting = Greeting()
    greeting.save()

    greetings = Greeting.objects.all()

    greetings_str = "\n".join([str(greeting.when) for greeting in greetings])
    return HttpResponse(greetings_str)

routines/templates/routines/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="/static/workouts/icons/logo1_16.png"> -->

    <title>{% block title %}WOD Benchmarks{% endblock %}</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'workouts/css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'workouts/css/style.css' %}" rel="stylesheet" type="text/css">
    
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <!-- <link href="starter-template.css" rel="stylesheet"> -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>



  <body>
    <nav class="navbar navbar-default">
      <div class="container">
      {% block sidebar %}
        <div id="navbar" class="">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'routines:index' %}">Home</a></li>
          </ul>
      {% endblock sidebar %}
      </div>
    </nav>

    <div id="content" class="container">
      {% block content %}{% endblock %}
    </div> <!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'workouts/js/bootstrap.js' %}"></script>
    <!-- <script src="../../static/workouts/js/bootstrap.min.js"></script> -->
    <!-- <script src="../../assets/js/docs.min.js"></script> -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
  </body>





</html>

routines/templates/routines/index.html
{% extends "./base.html" %}

{% block content %}
<div class="page-header"><h1>{% block title %}WODs{% endblock %}</h1></div>

<div class="wod-block">
  <div class="wod-title">Fran</div>
  <div class="wod-description">
    <ul class="list-unstyled">
      21 thrusters 75/95 lbs<br>
      21 pull ups<br>
      15 thrusters 75/95 lbs<br>
      15 pull ups<br>
      9  thrusters 75/95 lbs<br>
      9  pull ups
    </ul>
  </div>
  <div class="wod-type">
    For time
  </div>
  <div class="wod-result-stats">
    <table class="table table-hover"> 
      <caption>Typical WOD results based on crossfit.com entries.</caption> 
      <thead> 
        <tr> 
          <th>Scale</th> 
          <th>Low</th> 
          <th>High</th> 
        </tr> 
      </thead> 
      <tbody> 
        <tr>
          <th scope="row">Rx'd Male</th> 
          <td>4:30</td> 
          <td>5:30</td> 
        </tr> 
        <tr> 
          <th scope="row">Rx'd Female</th> 
          <td>5:00</td> 
          <td>5:45</td> 
        </tr>
        <tr> 
          <th scope="row">Rx'd Masters</th> 
          <td>6:00</td>
          <td>7:30</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

routines/templates/routines/index_dynamic.html
{% extends "./base.html" %}

{% block content %}
<div class="page-header"><h1>{% block title %}WODs{% endblock %}</h1></div>

<div class="wod-block">
  <div class="wod-title">{{ workout.title }}</div>
  <div class="wod-description">
    <ul class="list-unstyled">
      {{ workout.description }}
    </ul>
  </div>
  <div class="wod-type">
    For time
  </div>
  <div class="wod-result-stats">
    <table class="table table-hover"> 
      <caption>Typical WOD results based on crossfit.com entries.</caption> 
      <thead> 
        <tr> 
          <th>Scale</th> 
          <th>Best</th> 
          <th>Avg</th> 
          <th>Worst</th>
        </tr> 
      </thead> 
      <tbody> 
        <tr>
          <th scope="row">Rx'd All</th> 
          <td>{{ workout.results_best }}</td> 
          <td>{{ workout.results_avg }}</td> 
          <td>{{ workout.results_worst }}</td>
        </tr> 
        <tr>
          <th scope="row">Rx'd Male</th> 
          <td>{{ workout.results_best_male }}</td> 
          <td>{{ workout.results_avg_male }}</td> 
          <td>{{ workout.results_worst_male }}</td>
        </tr> 
        <tr> 
          <th scope="row">Rx'd Female</th> 
          <td>{{ workout.results_best_female }}</td> 
          <td>{{ workout.results_avg_female }}</td> 
          <td>{{ workout.results_worst_female }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}